export const alarms = [
  {
    id: "A1",
    name: "Alta Temperatura Motor Principal",
    type: "Temperature",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A2",
    name: "Baja Presión de Aceite",
    type: "Pressure",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A3",
    name: "Falla Sensor Voltaje",
    type: "Voltage",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A4",
    name: "Bomba Sentina Fallida",
    type: "PumpFailure",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A5",
    name: "Nivel Agua Bajo",
    type: "WaterLevel",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A6",
    name: "Fuga de Combustible Detectada",
    type: "FuelLeak",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A7",
    name: "Humo Detectado",
    type: "Smoke",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A8",
    name: "Corriente de Arranque Excesiva",
    type: "Current",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A9",
    name: "Bajo Nivel de Refrigerante",
    type: "CoolantLevel",
    delay: 2500,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A10",
    name: "Alta Temperatura de Escape",
    type: "ExhaustTemp",
    delay: 1200,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A11",
    name: "Baja Tensión General",
    type: "Voltage",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A12",
    name: "Fuego Detectado",
    type: "Fire",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A13",
    name: "RPM Motor Elevadas",
    type: "RPM",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A14",
    name: "Sobre RPM Permitidas",
    type: "RPM",
    delay: 800,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A15",
    name: "Bajo Nivel Combustible",
    type: "FuelLevel",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A16",
    name: "Vibración Excesiva",
    type: "Vibration",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A17",
    name: "Puerta Abierta",
    type: "DoorOpen",
    delay: 0,
    inhibit: false,
    state: 1,
    group: 6,
  },
  {
    id: "A18",
    name: "Alta Temperatura Caja Reductora",
    type: "Temperature",
    delay: 1800,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A19",
    name: "Voltaje Excesivo",
    type: "Voltage",
    delay: 800,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A20",
    name: "Fallo Batería Principal",
    type: "Battery",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A21",
    name: "Vibración Caja Crítica",
    type: "Vibration",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A22",
    name: "Nivel Combustible Crítico",
    type: "FuelLevel",
    delay: 1800,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A23",
    name: "Bajo Nivel Aceite Crítico",
    type: "OilLevel",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A24",
    name: "Alta Agua Sentina",
    type: "WaterLevel",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A25",
    name: "Falla Bomba Sentina Crítica",
    type: "PumpFailure",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A26",
    name: "Falla Sistema Alarma",
    type: "SystemFailure",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A27",
    name: "Alta Temperatura Motor Crítica",
    type: "Temperature",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A28",
    name: "Baja Presión Aceite Crítica",
    type: "Pressure",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A29",
    name: "Falla Sensor Voltaje Crítica",
    type: "Voltage",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A30",
    name: "Bomba Sentina Fallida Crítica",
    type: "PumpFailure",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A31",
    name: "Nivel Agua Muy Bajo",
    type: "WaterLevel",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A32",
    name: "Fuga de Combustible Grave",
    type: "FuelLeak",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A33",
    name: "Humo Denso Detectado",
    type: "Smoke",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A34",
    name: "Corriente de Arranque Peligrosa",
    type: "Current",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A35",
    name: "Bajo Nivel de Refrigerante Crítico",
    type: "CoolantLevel",
    delay: 2500,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A36",
    name: "Alta Temperatura de Escape Crítica",
    type: "ExhaustTemp",
    delay: 1200,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A37",
    name: "Baja Tensión General Crítica",
    type: "Voltage",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A38",
    name: "Fuego Extenso Detectado",
    type: "Fire",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 6,
  },
  // Group 1: Motor Principal
  {
    id: "A39",
    name: "Falla de Inyección Motor",
    type: "InjectionFailure",
    delay: 1200,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A40",
    name: "Sobrecalentamiento Turbo",
    type: "TurboTemp",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 1,
  },

  // Group 2: Caja Reductora
  {
    id: "A41",
    name: "Baja Presión Caja Reductora",
    type: "Pressure",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A42",
    name: "Falla Engranaje Principal",
    type: "GearFailure",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 2,
  },

  // Group 3: Sistema Eléctrico
  {
    id: "A43",
    name: "Corto Circuito Detectado",
    type: "ShortCircuit",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A44",
    name: "Fallo Generador Principal",
    type: "GeneratorFailure",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 3,
  },

  // Group 4: Niveles
  {
    id: "A45",
    name: "Nivel de Aceite Bajo",
    type: "OilLevel",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A46",
    name: "Nivel de Agua Crítico",
    type: "WaterLevel",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 4,
  },

  // Group 5: Sentina
  {
    id: "A47",
    name: "Obstrucción en Bomba Sentina",
    type: "PumpBlockage",
    delay: 1800,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A48",
    name: "Fuga de Agua en Sentina",
    type: "WaterLeak",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 5,
  },

  // Group 6: Misceláneos
  {
    id: "A49",
    name: "Puerta de Emergencia Abierta",
    type: "DoorOpen",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A50",
    name: "Falla en Sistema de Alarma",
    type: "SystemFailure",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A51",
    name: "Falla en Sensor de Temperatura",
    type: "Temperature",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 1,
  },
  {
    id: "A52",
    name: "Baja Presión en Sistema Hidráulico",
    type: "Pressure",
    delay: 1200,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A53",
    name: "Corto en Circuito de Iluminación",
    type: "ShortCircuit",
    delay: 800,
    inhibit: false,
    state: 1,
    group: 3,
  },
  {
    id: "A54",
    name: "Nivel de Combustible Bajo Crítico",
    type: "FuelLevel",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A55",
    name: "Obstrucción en Tubería de Sentina",
    type: "PumpBlockage",
    delay: 1800,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A56",
    name: "Puerta de Cabina Abierta",
    type: "DoorOpen",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A57",
    name: "Sobrecalentamiento Caja",
    type: "Temperature",
    delay: 1500,
    inhibit: false,
    state: 1,
    group: 2,
  },
  {
    id: "A58",
    name: "Falla en Generador Auxiliar",
    type: "GeneratorFailure",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A59",
    name: "Nivel de Aceite Crítico",
    type: "OilLevel",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A60",
    name: "Fuga de Agua en Tanque de Sentina",
    type: "WaterLeak",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A61",
    name: "Falla en Sistema de Alarma Principal",
    type: "SystemFailure",
    delay: 0,
    inhibit: false,
    state: 1,
    group: 6,
  },

  {
    id: "A64",
    name: "Baja Presión en Caja Reductora",
    type: "Pressure",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A65",
    name: "Corto Circuito en Sistema de Control",
    type: "ShortCircuit",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A66",
    name: "Nivel de Agua Bajo en Tanque",
    type: "WaterLevel",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A67",
    name: "Obstrucción en Filtro de Sentina",
    type: "PumpBlockage",
    delay: 1800,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A68",
    name: "Puerta de Sala de Máquinas Abierta",
    type: "DoorOpen",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },

  {
    id: "A70",
    name: "Falla en Engranaje Secundario",
    type: "GearFailure",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A71",
    name: "Falla en Batería Auxiliar",
    type: "Battery",
    delay: 1500,
    inhibit: false,
    state: 5,
    group: 3,
  },
  {
    id: "A72",
    name: "Nivel de Refrigerante Bajo",
    type: "CoolantLevel",
    delay: 2500,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A73",
    name: "Fuga de Combustible en Sentina",
    type: "FuelLeak",
    delay: 0,
    inhibit: false,
    state: 4,
    group: 5,
  },
  {
    id: "A74",
    name: "Falla en Sensor de Humo",
    type: "Smoke",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 6,
  },

  {
    id: "A76",
    name: "Baja Presión de Lubricación",
    type: "Pressure",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A77",
    name: "Falla en Generador de Emergencia",
    type: "GeneratorFailure",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A78",
    name: "Nivel de Aceite Bajo en Motor",
    type: "OilLevel",
    delay: 1000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A79",
    name: "Fuga de Agua en Sistema de Sentina",
    type: "WaterLeak",
    delay: 1500,
    inhibit: false,
    state: 1,
    group: 5,
  },
  {
    id: "A80",
    name: "Falla en Sistema Secundario",
    type: "SystemFailure",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },
  {
    id: "A81",
    name: "Vibración Excesiva en Caja Reductora",
    type: "Vibration",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 2,
  },
  {
    id: "A82",
    name: "Falla en Sensor de Corriente",
    type: "Current",
    delay: 800,
    inhibit: false,
    state: 2,
    group: 3,
  },
  {
    id: "A83",
    name: "Nivel de Agua Crítico en Tanque",
    type: "WaterLevel",
    delay: 2000,
    inhibit: false,
    state: 3,
    group: 4,
  },
  {
    id: "A84",
    name: "Obstrucción en Línea de Sentina",
    type: "PumpBlockage",
    delay: 1800,
    inhibit: false,
    state: 2,
    group: 5,
  },
  {
    id: "A85",
    name: "Puerta de Acceso Abierta",
    type: "DoorOpen",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },

  {
    id: "A87",
    name: "Falla en Engranaje Principal",
    type: "GearFailure",
    delay: 2000,
    inhibit: false,
    state: 8,
    group: 2,
  },
  {
    id: "A88",
    name: "Falla en Sistema de Iluminación",
    type: "ShortCircuit",
    delay: 500,
    inhibit: false,
    state: 0,
    group: 3,
  },
  {
    id: "A89",
    name: "Nivel de Combustible Bajo",
    type: "FuelLevel",
    delay: 2000,
    inhibit: false,
    state: 0,
    group: 4,
  },
  {
    id: "A90",
    name: "Fuga de Agua en Bomba de Sentina",
    type: "WaterLeak",
    delay: 1500,
    inhibit: false,
    state: 0,
    group: 5,
  },
  {
    id: "A91",
    name: "Falla en Sensor de Puerta",
    type: "DoorOpen",
    delay: 0,
    inhibit: false,
    state: 0,
    group: 6,
  },
];
